import * as vscode from 'vscode';

export class GeneratedCodeProvider implements vscode.TreeDataProvider<vscode.TreeItem> {

    private _onDidChangeTreeData: vscode.EventEmitter<vscode.TreeItem | undefined | void> = new vscode.EventEmitter<vscode.TreeItem | undefined | void>();
    readonly onDidChangeTreeData: vscode.Event<vscode.TreeItem | undefined | void> = this._onDidChangeTreeData.event;

    private generatedCode: vscode.TreeItem[] = [];

    // his triggers a refresh so that the new code appears in the sidebar.
    refresh(): void {
        this._onDidChangeTreeData.fire();
    }

    // This method updates the sidebar with the code generated by Code Llama.
    updateGeneratedCode(code: string): void {
        this.generatedCode = [new vscode.TreeItem(code)];
        this.refresh();
    }

    // Get individual TreeItem (only one in this case for generated code)
    getTreeItem(element: vscode.TreeItem): vscode.TreeItem {
        return element;
    }

    // Get children TreeItems (in this case, the generated code)
    getChildren(): vscode.TreeItem[] {
        return this.generatedCode;
    }
}
